export const SAVE_TOKENS = 'SAVE_TOKENS';
export const SAVE_TOKENS_INFO = 'SAVE_TOKENS_INFO';
export const LOAD_USERINFO_FROM_STORAGE = 'LOAD_USERINFO_FROM_STORAGE';
export const LOAD_TOKENS_FROM_STORAGE = 'LOAD_TOKENS_FROM_STORAGE';
export const LOGOUT = 'LOGOUT';
